### ISSUE TITLE
CreateSignatureScript: "psobject" to type "Object".

### ISSUE THREAD

**Issue by JWalters-DravenIT** [chrisred/posh-scripts#2]
Love the script.  Excellent versioning and setting in Outlook.

When running, I get the following error:
Exception setting "SaveAs": Cannot convert the "file" value of type "psobject" to type "Object".

From Lines 254, 257, 260
254: $Word.ActiveDocument.SaveAs([Ref]$SavePath, [Ref][Microsoft.Office.Interop.Word.WdSaveFormat]::wdFormatHTML)

Office 365 ProPlus, Word: 16.0.10730.20264 32-bit
Powershell:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  2879

**Comment by JWalters-DravenIT** [comment]
I solved it after a small inspiration.

On line 253, declare the $SavePath as a string

253: [String}$SavePath = ...

**Comment by chrisred** [comment]
Hey, thanks for the details on this. I'll take a look at in in more detail when i have some free time, this does look similar another issue that was reported to me.

**Comment by JWalters-DravenIT** [comment]
Let me just thank you for this script. It is the best I have found and solved a big problem on my end. Again, Thank you.

On Jun 15, 2019, at 7:05 PM, Chris Redit <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, thanks for the details on this. I'll take a look at in in more detail when i have some free time, this does look similar another issue that was reported to me.
