### ISSUE TITLE
CreateSignature Script Error

### ISSUE THREAD

**Issue by Nickvlc** [chrisred/posh-scripts#3]
I have a new Windows 10 with Office 2016 from O365 and when run the script get this error:

"The assembly 'Microsoft.Office.Interop.Word' could not be loaded, Microsoft Word must be installed"

But the PC has the Office installed ¿?

**Comment by chrisred** [comment]
Not see this myself or had it reported anywhere else. Not sure what would cause this without more info. Sorry.
