### ISSUE TITLE
Preserve formatting on the {mail} variable

### ISSUE THREAD

**Issue by ghost** [chrisred/posh-scripts#7]
Currently if you format the text '{mail}' in the template, for example making the text a certain colour, then run the script - the text in the signature won't follow the original formatting.

It looks like when the script expands {mail} into the user's email, and creates a hyperlink with the appropriate mailto link, it ends up stripping any formatting and the email would be the default link format.

**Comment by chrisred** [comment]
Yes, it replaced the {mail} or {emailAddress} properties with a "mailto:" link. Added an option to turn off the mailto links in v1.3.

https://github.com/chrisred/posh-scripts/blob/master/OutlookSignatureScript.ps1

**Comment by ghost** [comment]
Thanks for the extra function, although the scenario I'm thinking about is where the '{mail}' text was formatted in a certain way - text colour set to red for example.

When the script is ran the final signature would have '{mail}' replaced with the actual AD variable and would have been hyperlinked with the appropriate 'mailto:' link, but the formatting would have been lost because of the creation of the hyperlink. I understand your extra function would mean that the formatting would no longer be lost because no hyperlink would be created for that text.

Is there a way to hyperlink the text while keeping the original text's formatting for the new hyperlinked text? I know you're using Word's engine for this manipulation so if there is a limitation where you can't copy the formatting before the operation and re-impose that same formatting after the operation, then it would be completely understandable to not be able to implement this request! I know Word is probably resetting formatting to the default for the type of text 'hyperlink' when you're adding the 'mailto:'.

**Comment by chrisred** [comment]
I see, you can change this for the template you use in Word.

Edit the default "hyperlink" style to something that fits better. For instance remove the blue colour change and just have it underline. Or remove the style completely.

**Comment by ghost** [comment]
Can't believe I didn't think of changing the default hyperlink style in the Word file, thanks!
