### ISSUE TITLE
Don't insert a line when the variable is blank

### ISSUE THREAD

**Issue by ghost** [chrisred/posh-scripts#8]
Could we have an option for the script to not insert a line at all when a variable is blank?
If the script had a toggle to not generate a line if any variables on that line were blank, it would fulfill the #5 request as well.

### Scenario
Let's say I have the following template:
{displayName}
{title}
{telephoneNumber}
{mobile}
{mail}

But the user doesn't have any phone numbers

### Actual output

User's display name
User's title
Blank line here
Blank line here
User's email

### Intended output

User's display name
User's title
User's email

**Comment by chrisred** [comment]
Thanks, removing the line is a simple solution. An option to enable this is added in v1.3.

https://github.com/chrisred/posh-scripts/blob/master/OutlookSignatureScript.ps1
